name: Build Flask Executable with PyInstaller

on:
  push:
    branches:
      - Wip  # Trigger on pushes to main branch

jobs:
  build_executable:
    runs-on: ubuntu-latest  # Run the job on an Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set up Python 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies if requirements.txt exists

      - name: Build Executable with PyInstaller
        run: |
          python -m PyInstaller --onefile --add-data "templates:templates" --add-data "static:static" --name mimosa.exe app.py  # Build the executable

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flask-executable
          path: dist/mimosa.exe  # Upload the built executable from the dist folder
