name: Build Windows Executable with PyInstaller

on:
  push:
    branches:
      - Main  # Trigger on pushes to main branch

jobs:
  build_executable:
    runs-on: windows-latest  # Run the job on a Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Checkout the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Set up Python 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
        shell: pwsh

      - name: Build Executable with PyInstaller
        run: |
          pyinstaller --onefile --add-data "templates;templates" --add-data "static;static" --add-data "favicon.ico;." --name mimosa app.py
          Move-Item "dist/mimosa.exe" "mimosa.exe"  # Move the executable to the root directory
        shell: pwsh

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mimosa-executable
          path: mimosa.exe  # Upload the executable from the root directory
